### ISSUE TITLE
unable to start

### ISSUE THREAD

**Issue by soh7app** [noveoko/soaicode#1]
![error1111](https://user-images.githubusercontent.com/84973038/119992565-1de61a00-bfe4-11eb-9a36-47fe4515d14e.png)
Please guide I am facing this error

**Comment by soh7app** [comment]
@noveoko

**Comment by mrkatey** [comment]
Invalid URL ---> you need to have access to GPT-3 (as a user) otherwise you will not be able to run this code. To get access you have to sign up at the openai web site.
